image: alpine:latest

before_script:
  - apk add --quiet openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts

deploy:
  script:
    # Deploy
    - ssh -o StrictHostKeyChecking=no knowledge@knowledge.msharks.ru "cd ~/knowledge.msharks.ru/code/ && git pull && git checkout dev && docker-compose stop php-http && docker-compose up -d php-http && docker exec -i kb_php_http composer install && docker exec -i kb_php_http php artisan migrate"
  only:
    - dev
