<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

abstract class Material extends Model
{
    protected static $sectionId = null;

    protected $keyType = 'string';

    public $incrementing = false;

    public static function configure(Section $section): void
    {
        foreach ($section->relationLoaders() as $key => $loader) {
            self::resolveRelationUsing($key, $loader);
        }
    }
//
//    public function getRelation($relation)
//    {
//        return isset(static::$relationResolvers[static::class][$relation])
//            ? (static::$relationResolvers[static::class][$relation])($this)
//            : parent::getRelation($relation);
//    }

    public function getRelationValue($key)
    {
    }

    protected static function booting()
    {
        static::configure(Section::findOrFail(static::$sectionId));
    }

    public function toArray()
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }
}
