<?php

declare(strict_types=1);

namespace App\Models;


use Illuminate\Database\Eloquent\Model;

/**
 * @property string $id
 * @property string $name
 */
abstract class Material extends Model
{
    public static $sectionId = null;

    protected $keyType = 'string';

    public $incrementing = false;

    public static function configure(Section $section): void
    {
        foreach ($section->relationLoaders() as $key => $loader) {
            self::resolveRelationUsing($key, $loader);
        }
    }

    protected static function booting(): void
    {
        static::configure(Section::findOrFail(static::$sectionId));
    }

    public function toArray(): array
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

    public function getSectionIdAttribute()
    {
        return static::$sectionId;
    }
}
